remote_theme: swift-island
title: "Swift Island"
description: "An experimental Swift conference on an actual island."
sub-title: "An experimental conference happening after Apple's WWDC 2020."
author: "Niels van Hoorn, Sidney de Koning"
baseurl: ""
twitter: "https://twitter.com/swiftislandnl"
email: "info@swiftisland.nl"
edition-year: "2020"
edition-date: "August 25 - 27"
from-ticket-price: "€799"
ticket-amount: "60"
presale: true
collections:
  - mentors
  - activites
  - faqs
  - sponsors
