remote_theme: swift-island
title: "Swift Island"
description: "An experimental Swift conference on an actual island."
sub-title: "An experimental conference happening after Apple's WWDC 2018."
author: "Niels van Hoorn, Sidney de Koning"
baseurl: ''
twitter: "https://twitter.com/swiftislandnl"
email: "info@swiftisland.nl"
collections:
  - mentors
  - activites
  - faqs
  - sponsors
